import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import LoginPromptModal from "@/components/LoginPromptModal";
import RouteLoader from "@/components/RouteLoader";
import NgoVerificationModal from "@/components/NgoVerificationModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Font Awesome for social icons */}
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} m-0 p-0 antialiased`}
      >
        <RouteLoader>
        <Navbar />
        <main className="w-full">{children}</main>
        <Footer />
        </RouteLoader>
        <LoginPromptModal />
        <NgoVerificationModal />
      </body>
    </html>
  );
}
